### ISSUE TITLE
Airbnb price regression, dataset unzip error

### ISSUE THREAD

**Issue by manugarri** [combust/mleap-demo#5]
Following the tutorial on https://github.com/combust/mleap-demo/blob/master/notebooks/airbnb-price-regression.ipynb  , I downloaded the dataset from https://s3-us-west-2.amazonaws.com/mleap-demo/datasources/airbnb.avro.zip  . However the file cant be unzipped, and fails with the error:

```Archive:  airbnb.avro.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  airbnb.avro.zip may be a plain executable, not an archive
unzip:  cannot find zipfile directory in one of airbnb.avro.zip or
        airbnb.avro.zip.zip, and cannot find airbnb.avro.zip.ZIP, period.
```

**Comment by ancasarb** [comment]
@manugarri I had the same issue and I don't remember for sure, but I think I managed to find the airbnb.avro on the old mleap github repo somewhere I think. I couldn't attach it here directly because it's bigger than 10mb, but below is a google drive link to the avro file  

https://drive.google.com/file/d/0B6QOjABLM2azeHFPbHJub3FvUnc/view?usp=sharing

**Comment by manugarri** [comment]
Wow, thanks @ancasarb ! Maybe the repo admin can add it to the examples again? Im starting to think this project is not going very well to be honest, docs are mostly abandoned

**Comment by ancasarb** [comment]
@manugarri I believe that the documentation available under http://mleap-docs.combust.ml/ is up to date, nevertheless, I've created issue https://github.com/combust/mleap/issues/185 to make sure the demos work with the latest version of mleap (0.6.0), I think the reason you're running into issues is because the mleap version used in the demos is 0.5.0.

**Comment by manugarri** [comment]
might be, thanks for the heads up, will try again with the newer version
